import { writeFileSync } from "fs";
import path from "path";

export async function createFile(name: string, ext: string, content: string) {
  const modified = `public/files/${name}.${ext}`;
  const project_dir = process.cwd();
  const newPath = path.join(project_dir, modified);

  writeFileSync(newPath, content ?? "File generated by Groq", {
    encoding: "utf8",
  });
}
