import { writeFileSync } from "fs";
import path from "path";
import pdf from "pdf-parse";

export async function createFile(name: string, content: string) {
  const modified = `public/files/${name}`;
  const project_dir = process.cwd();
  const newPath = path.join(project_dir, modified);

  writeFileSync(newPath, content ?? "File generated by Groq", {
    encoding: "utf8",
  });
}

export async function readPDF(url: string) {
  console.log("Url is here", url);
  if (!url) {
    return;
  }
  const pdfUrl = url;

  const response = await fetch(pdfUrl);
  const buffer = Buffer.from(await response.arrayBuffer());
  const data = await pdf(buffer);

  console.log(data.text);
  return data.text;
}
